## Reading Data From Different Sources

Using in-built functions in Pandas

In [ ]:
import pandas as pd
from io import StringIO

## Read JSON data into DataFrame
data = '{"employee_name": "Rohit", "email": "ro@hello.com", "job_title": [{"titile1": "Data Scientist"}, {"title2": "ML Engineer"}]}'
df = pd.read_json(StringIO(data))
df

  employee_name         email                      job_title
0         Rohit  ro@hello.com  {'titile1': 'Data Scientist'}
1         Rohit  ro@hello.com      {'title2': 'ML Engineer'}

In [ ]:
## Convert DataFrame back to JSON
json_data = df.to_json()
print("This created as key-value for each column.\n", json_data)

This created as key-value for each column.
 {"employee_name":{"0":"Rohit","1":"Rohit"},"email":{"0":"ro@hello.com","1":"ro@hello.com"},"job_title":{"0":{"titile1":"Data Scientist"},"1":{"title2":"ML Engineer"}}}

In [ ]:
## Using orient parameter to change the format with 'index'
json_data_index = df.to_json(orient='index')
print("\nThis created as key-value for each row (index).\n", json_data_index)

This created as key-value for each row (index).
 {"0":{"employee_name":"Rohit","email":"ro@hello.com","job_title":{"titile1":"Data Scientist"}},"1":{"employee_name":"Rohit","email":"ro@hello.com","job_title":{"title2":"ML Engineer"}}}

In [15]:
## Orient options include 'split', 'records', 'index', 'columns', and 'values'.
json_data_records = df.to_json(orient='records')
print("\nThis created as list of records (dictionaries) for each row.\n", json_data_records),

This created as list of records (dictionaries) for each row.
 [{"employee_name":"Rohit","email":"ro@hello.com","job_title":{"titile1":"Data Scientist"}},{"employee_name":"Rohit","email":"ro@hello.com","job_title":{"title2":"ML Engineer"}}]

(None,)

In [ ]:
## Using URL (csv) to read JSON data
df=pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data",header=None)
df.head()
## Header = None indicates that the file does not contain column names, so pandas will assign default integer column names (0, 1, 2, ...).

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

In [19]:
df.to_csv("output.csv")

In [26]:
## Reading data from HTTP URL
url = "https://www.bankbazaar.com/tax/7th-pay-commission-pay-matrix-table.html"

df = pd.read_html(url)

In [22]:
%pip install lxml html5lib beautifulsoup4

Collecting lxml
  Downloading lxml-6.0.2-cp312-cp312-win_amd64.whl.metadata (3.7 kB)
Collecting html5lib
  Using cached html5lib-1.1-py2.py3-none-any.whl.metadata (16 kB)
Collecting beautifulsoup4
  Using cached beautifulsoup4-4.14.3-py3-none-any.whl.metadata (3.8 kB)
Requirement already satisfied: six>=1.9 in d:\ai\udemyhandson\machinelearning\venv\lib\site-packages (from html5lib) (1.17.0)
Collecting webencodings (from html5lib)
  Using cached webencodings-0.5.1-py2.py3-none-any.whl.metadata (2.1 kB)
Collecting soupsieve>=1.6.1 (from beautifulsoup4)
  Using cached soupsieve-2.8-py3-none-any.whl.metadata (4.6 kB)
Collecting typing-extensions>=4.0.0 (from beautifulsoup4)
  Using cached typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Downloading lxml-6.0.2-cp312-cp312-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ------- -------------------------------- 0.8/4.0 MB 11.2 MB/s eta 0:00:01
   ---------------------------------------- 4.0/4.0 MB 14.1 MB/s  0:00:00
Using cached html5lib-1.1-py2.py3-none-any.whl (112 kB)
Using cached beautifulsoup4-4.14.3-py3-none-any.whl (107 kB)
Using cached soupsieve-2.8-py3-none-any.whl (36 kB)
Using cached typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Using cached webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Installing collected packages: webencodings, typing-extensions, soupsieve, lxml, html5lib, beautifulsoup4

   ---------------------------------------- 0/6 [webencodings]
   ------ --------------------------------- 1/6 [typing-extensions]
   ------------- -------------------------- 2/6 [soupsieve]
   ------------- -------------------------- 2/6 [soupsieve]
   -------------------- ------------------- 3/6 [lxml]
   -------------------- ------------------- 3/6 [lxml]
   -------------------- ------------------- 3/6 [lxml]
   -------------------- ------------------- 3/6 [lxml]
   -------------------- ------------------- 3/6 [lxml]
   -------------------- ------------------- 3/6 [lxml]
   -------------------- ------------------- 3/6 [lxml]
   -------------------- ------------------- 3/6 [lxml]
   -------------------------- ------------- 4/6 [html5lib]
   -------------------------- ------------- 4/6 [html5lib]
   -------------------------- ------------- 4/6 [html5lib]
   -------------------------- ------------- 4/6 [html5lib]
   -------------------------- ------------- 4/6 [html5lib]
   -------------------------- ------------- 4/6 [html5lib]
   -------------------------- ------------- 4/6 [html5lib]
   -------------------------- ------------- 4/6 [html5lib]
   -------------------------- ------------- 4/6 [html5lib]
   --------------------------------- ------ 5/6 [beautifulsoup4]
   --------------------------------- ------ 5/6 [beautifulsoup4]
   --------------------------------- ------ 5/6 [beautifulsoup4]
   --------------------------------- ------ 5/6 [beautifulsoup4]
   ---------------------------------------- 6/6 [beautifulsoup4]

Successfully installed beautifulsoup4-4.14.3 html5lib-1.1 lxml-6.0.2 soupsieve-2.8 typing-extensions-4.15.0 webencodings-0.5.1
Note: you may need to restart the kernel to use updated packages.

In [28]:
df[1]

       GP    4200    4600    4800    5400
0   Level       6       7       8       9
1       1   35400   44900   47600   53100
2       2   36500   46200   49000   54700
3       3   37600   47600   50500   56300
4       4   38700   49000   52000   58000
5       5   39900   50500   53600   59700
6       6   41100   52000   55200   61500
7       7   42300   53600   56900   63300
8       8   43600   55200   58600   65200
9       9   44900   56900   60400   67200
10     10   46200   58600   62200   69200
11     11   47600   60400   64100   71300
12     12   49000   62200   66000   73400
13     13   50500   64100   68000   75600
14     14   52000   66000   70000   77900
15     15   53600   68000   72100   80200
16     16   55200   70000   74300   82600
17     17   56900   72100   76500   85100
18     18   58600   74300   78800   87700
19     19   60400   76500   81200   90300
20     20   62200   78800   83600   93000
21     21   64100   81200   86100   95800
22     22   66000   83600   88700   98700
23     23   68000   86100   91400  101700
24     24   70000   88700   94100  104800
25     25   72100   91400   96900  107900
26     26   74300   94100   99800  111100
27     27   76500   96900  102800  114400
28     28   78800   99800  105900  117800
29     29   81200  102800  109100  121300
30     30   83600  105900  112400  124900
31     31   86100  109100  115800  128600
32     32   88700  112400  119300  132500
33     33   91400  115800  122900  136500
34     34   94100  119300  126600  140600
35     35   96900  122900  130400  144800
36     36   99800  126600  134300  149100
37     37  102800  130400  138300  153600
38     38  105900  134300  142400  158200
39     39  109100  138300  146700  162900
40     40  112400  142400  151100  151100

In [32]:
url1 = "https://www.vedantu.com/jee-advanced/iits-btech-fee-structure"
## We can use other params like match, flavor, header, etc.
pd.read_html(url1, match="NIRF", header=0)

[   Indian Institute of Technology  NIRF 2024 Score  NIRF 2024 Rank
 0                      IIT Madras            90.04               1
 1                       IIT Delhi            88.12               2
 2                      IIT Bombay            83.96               3
 3                      IIT Kanpur            82.56               4
 4                   IIT Kharagpur            78.89               5
 5                     IIT Roorkee            76.70               6
 6                    IIT Guwahati            72.98               7
 7                   IIT Hyderabad            68.03               9
 8                    IIT Varanasi            63.51              13
 9                     IIT Dhanbad            63.50              14
 10                     IIT Indore            61.68              16
 11                      IIT Mandi            60.43              20
 12                      IIT Ropar            59.16              22
 13                IIT Gandhinagar            58.27              23
 14                    IIT Jodhpur            56.70              30
 15                      IIT Patna            56.19              33
 16                IIT Bhubaneswar            55.11              36]

In [36]:
## Reading and Writing Excel Files
df = pd.read_excel('data.xlsx')
df

    Name  Age
0  Krish   32
1   Jack   34
2   John   31

In [34]:
%pip install openpyxl

Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [ ]:
## Reading a pickle file
## Making xlsx to pickle file
df.to_pickle('df_pickle')

In [ ]:
## Read pickle file
pd.read_pickle('df_pickle')

    Name  Age
0  Krish   32
1   Jack   34
2   John   31

In [ ]:
pd.read_clipboard()

Empty DataFrame
Columns: [df, =, pd.DataFrame([[1,, 2,, 3],, [4,, 5,, 6]],, columns=['A',, 'B',, 'C'])]
Index: []

### Extra Learnings

1

JSON is a text format, and read_json is designed to read:\
1 JSON files\
2 JSON API responses (StringIO)\
3 JSON strings\
It is not designed to parse Python dictionaries directly.\

For inputing a dict, we can:\
1 Use json.dumps(data)\
2 pd.DataFrame.from_dict(data)/
3 Use StringIO which creates an in-memory buffer which acts like a json_file but is actually an object.\

2

To work with websites and pd, dependencies are needed.

3

A "pickle file" refers to a file created by the Python pickle module, which is used for serializing and deserializing Python objects.


Serialization (Pickling):\
This process converts a Python object hierarchy (like a list, dictionary, or a custom class instance) into a byte stream.\
This byte stream can then be written to a file, stored in a database, or transmitted over a network.
The act of converting an object into a byte stream is called "pickling."\
Deserialization (Unpickling):\ 
This is the inverse operation, where a byte stream (read from a file or received over a network) is converted back into a Python object hierarchy.\
The act of converting a byte stream back into an object is called "unpickling."\
Key characteristics of pickle files:\
Python-specific: Pickle is designed specifically for Python objects and is not typically compatible with other programming languages.\
Binary format: Pickle files store data in a binary format, making them efficient for storing complex Python objects.\
Versatility: Pickle can serialize almost any Python object, including functions, classes, and complex nested data structures. This is a key advantage over formats like JSON or XML, which have limitations in representing certain Python objects.\ 
Security concerns: A significant security consideration with pickle is that unpickling data from untrusted sources can lead to the execution of arbitrary code, as the pickle format can include instructions for reconstructing objects, including calling functions. Therefore, never unpickle data from untrusted sources.


Common uses of pickle files:
Saving and loading application state: Persisting the state of a program between sessions.\
Caching computations: Storing the results of expensive computations to avoid re-running them.\
Persisting machine learning models: Saving trained machine learning models for later use without needing to retrain them.\
Transmitting Python objects: Sending Python objects between different processes or systems within a Python environment.