In [1]:
import pandas as pd

df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [24, 30, 22, 35],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston']
})

In [2]:
df = df.drop('Age', axis=1)

In [4]:
df.drop('City', axis=1)

      Name
0    Alice
1      Bob
2  Charlie
3    David

In [5]:
df

      Name         City
0    Alice     New York
1      Bob  Los Angeles
2  Charlie      Chicago
3    David      Houston