## Handling Imbalanced Datasets

An imbalanced dataset is one where the classes in the target variable are not represented equally.

Can be dealt with two basic methods:
1. Upsampling
2. Downsampling

In [2]:
import numpy as np
import pandas as pd

## Set random seed for reproducibility
np.random.seed(142)

# Create a DataFrame with two categories

n_samples = 10000
class_0_ratio = 0.85
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

In [3]:
n_class_0,n_class_1

(8500, 1500)

In [6]:
## Create DataFrame with impbalanced Dataset

class_0 = pd.DataFrame({
    'f1': np.random.normal(loc=0, scale=1,size=n_class_0),
    'f2': np.random.normal(loc=0,scale=1,size=n_class_0),
    't': [0] * n_class_0
})

class_1 = pd.DataFrame({
    'f1': np.random.normal(loc=2, scale=1,size=n_class_1),
    'f2': np.random.normal(loc=2,scale=1,size=n_class_1),
    't': [1] * n_class_1
})

In [7]:
df = pd.concat([class_0,class_1]).reset_index(drop=True)

In [8]:
df.head()

         f1        f2  t
0  0.129740  0.574385  0
1  0.902362 -0.423247  0
2  1.005804 -0.237009  0
3  0.471890 -1.642305  0
4 -0.326213  1.232260  0

In [11]:
df.sample(10)

            f1        f2  t
7869 -0.099504  0.326161  0
6042 -0.158398 -0.997784  0
5154 -1.171785 -1.268755  0
9358  2.287190  3.137119  1
9249  0.220835  0.916215  1
9748  2.620098  1.898521  1
879   0.530840 -0.098238  0
4565  0.203772  0.875868  0
1995 -0.261737 -0.324374  0
3694 -1.171354  1.387543  0

In [12]:
df['t'].value_counts()

t
0    8500
1    1500
Name: count, dtype: int64

### Upsampling Technique

In [17]:
## Create 2 DataFrames

df_minority=df[df['t']==1]
df_majority=df[df['t']==0]

In [18]:
# Upsampling with replacement of values
from sklearn.utils import resample
df_minortiy_upsampled = resample(df_minority, replace=True,  ## Sample with replacement
        n_samples=len(df_majority),
        random_state=22
)

In [ ]:
df_minortiy_upsampled.shape
## Shows we have created more datapoint with value = 1

(8500, 3)

In [21]:
df_upsampled = pd.concat([df_majority,df_minortiy_upsampled])

In [22]:
df_upsampled.sample(10)

            f1        f2  t
8628  1.442649  2.387670  1
9537  2.168797  2.259529  1
1531  0.311738 -0.902644  0
9203  1.856067  0.330326  1
9910  1.728628  2.122029  1
1012 -0.845998 -1.051690  0
3753 -0.575781 -0.823170  0
9587  1.626555  0.823985  1
9505  3.088791  1.468344  1
859  -2.095959  1.404622  0

In [ ]:
## Balanced DataSet
df_upsampled['t'].value_counts()

t
0    8500
1    8500
Name: count, dtype: int64

## Downsampling

In [25]:
## Creating the same DataFrame again

## Create DataFrame with impbalanced Dataset

class_0 = pd.DataFrame({
    'f1': np.random.normal(loc=0, scale=1,size=n_class_0),
    'f2': np.random.normal(loc=0,scale=1,size=n_class_0),
    't': [0] * n_class_0
})

class_1 = pd.DataFrame({
    'f1': np.random.normal(loc=2, scale=1,size=n_class_1),
    'f2': np.random.normal(loc=2,scale=1,size=n_class_1),
    't': [1] * n_class_1
})

df = pd.concat([class_0,class_1]).reset_index(drop=True)

# Check the class distribution
print(df['t'].value_counts())

t
0    8500
1    1500
Name: count, dtype: int64

In [ ]:
## Create 2 datasets

## Create 2 DataFrames

df_minority=df[df['t']==1]
df_majority=df[df['t']==0]

In [26]:
# Downsampling with replacement of values
from sklearn.utils import resample
df_majority_downsampled = resample(df_majority, replace=False,  ## Don't want to replace as we want to reduce the datapoints
        n_samples=len(df_minority),
        random_state=22
)

In [27]:
df_majority_downsampled.shape

(1500, 3)

In [29]:
df_downsamped = pd.concat([df_minority,df_majority_downsampled])
df_downsamped['t'].value_counts()

t
1    1500
0    1500
Name: count, dtype: int64

In [ ]:
## Downsampling is usually not used as it causes data loss